{{- range $namespace := .Values.namespaces -}}
{{- range $key, $secretproviderclass := $namespace.secretproviderclass -}}
{{-   $secretProviderSet := dict "namespace" $namespace -}}
{{-   if hasKey $secretProviderSet.namespace "secretproviderclass" -}}
{{-     $_ := merge $secretProviderSet (deepCopy $.Values.defaults) -}}
{{-     $_ := set $secretProviderSet "Release" $.Release -}}
{{-     $_ := set $secretProviderSet "Values" (deepCopy $.Values) -}}
{{-     $_ := set $secretProviderSet "secretproviderclass" $secretproviderclass -}}
{{-     $_ := set $secretProviderSet "secretName" $key -}}
---
{{      template "secretproviderclass" $secretProviderSet }}
---
{{-   end -}}
{{- end -}}
{{- end -}}
