---
# Source: helm-rails/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-app-env
  namespace: default
  labels:
    app.kubernetes.io/component: env
    app.kubernetes.io/instance: production
    app.kubernetes.io/name: example-app
    app.kubernetes.io/version: "458cd7e"
    app.kubernetes.io/managed-by: Helm
    initiator: githubActions
data:
  APPLICATION_HOST: example.com
  AWS_REGION: us-east-1
  LANG: en_US.UTF-8
  NODE_ENV: production
  PORT: "3000"
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: enabled
  RAILS_SERVE_STATIC_FILES: enabled
