---
# Source: helm-rails/templates/secretproviderclass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secretsmanager
  namespace: default
  labels:
    app.kubernetes.io/instance: production
    app.kubernetes.io/name: example-app
    app.kubernetes.io/version: "458cd7e"
    app.kubernetes.io/managed-by: Helm
    initiator: githubActions
spec:
  parameters:
      objects: |
        - objectName: default-secrets-one
          objectType: secretsmanager
          jmesPath:
          - path: HOST_NAME
            objectAlias: HOST_NAME
          - path: PROTOCOL
            objectAlias: PROTOCOL
          - path: USERNAME
            objectAlias: USERNAME
        - objectName: default-secrets-two
          objectType: secretsmanager
          jmesPath:
          - path: HASH
            objectAlias: HASH
          - path: SALT
            objectAlias: SALT
  provider: aws
  secretObjects:
  - secretName: secretsmanager
    type: Opaque
    data:
    - key: HOST_NAME
      objectName: HOST_NAME
    - key: PROTOCOL
      objectName: PROTOCOL
    - key: USERNAME
      objectName: USERNAME
    - key: HASH
      objectName: HASH
    - key: SALT
      objectName: SALT
