name: Run Helm CI Tests
# on:
# - push

on:
  push:

defaults:
  run:
    working-directory: charts/helm-rails

jobs:
  test:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: make tests 

    - name: Generate example
      run: make template-test 

    - name: Install kubeval
      uses: lra/setup-kubeval@v1

    - name: Validate example
      run: make kubeval  
